language: python
python:
  - "3.7"
install:
  - pip install codecov pytest-cov
  - pip install pytest-mpl
  - pip install pandas
  - pip install textblob
  - pip install nltk
  - pip install datetime
  - pip install seaborn
  - pip install plotly
  - pip install keyring==2.0.0
script:
  - pytest --cov=reviewminer tests
after_success:
  - codecov
