language: python
python:
  - "3.7"
install:
  - pip install codecov pytest-cov
  - pip install pandas
  - pip install textblob
  - pip install nltk
  - nltk.download('brown')
script:
  - pytest --cov=src tests
after_success:
  - codecov
